[[main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = 1

[[main]]
  identifier = "portfolio"
  name = "Portfolio"
  url = "/portfolio/"
  weight = 2

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "/archives/"
  weight = 4

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 5

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 6
