[module]

  [module.hugoVersion]
    extended = true
    min = "0.152.2"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/bootstrap/scss"

  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "assets/bootstrap/dist/js"

  [[module.mounts]]
    source = "node_modules/@popperjs/core/dist/umd"
    target = "assets/@popperjs/core/dist/umd"

  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font"
    target = "assets/bootstrap-icons/font"

[[module.imports]]
  path = "github.com/razonyang/hugo-theme-bootstrap/v1"
  version = "v1.13.2"
