[module]
  [module.hugoVersion]
    extended = true
    min = "0.152.2"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.imports]]
    path = "github.com/razonyang/hugo-theme-bootstrap"
    version = "v1.13.2"
