[build]
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.0"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "npm install && hugo --minify"

[context.deploy-preview]
  command = "npm install && hugo --minify -D"

[[redirects]]
  from = "https://www.aliefk.dev/*"
  to   = "https://aliefk.dev/:splat"
  status = 301
  force  = true

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' https://static.cloudflareinsights.com https://challenges.cloudflare.com https://giscus.app; connect-src 'self' https://cloudflareinsights.com; font-src 'self' data:; frame-src 'self' https://challenges.cloudflare.com https://giscus.app; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self';"
    Cache-Control = "public, max-age=600, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/offline.html"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"
